### ISSUE TITLE
Special instruction for Sword of the stars

### ISSUE THREAD

**Issue by rapenne-s** [rfht/fnaify#38]
The game is looking for Content/ui repertory and not the Content/UI that comes from the installer. Creating a symbolic link works.

```
ln -s UI Content/ui
```

The game also requires MONO_FORCE_COMPAT=yes to run correctly.

**Comment by rfht** [comment]
> The game is looking for Content/ui repertory and not the Content/UI that comes from the installer. Creating a symbolic link works.

That's a casualty of  mono 6 abandoning MONO_IOMAP, see https://github.com/mono/mono/pull/17231/commits/fcfe71c517eea56c5a8486a398d64488dea89a0c.
The question is if other filenames may also be wrongly represented in the assembly. How much playtime did you do with this change? I'd like to test this a bit longer before adding the symlink to fnaify because if there should be too many files that are not found to really play it, there may need to be a different solution.

> The game also requires MONO_FORCE_COMPAT=yes to run correctly.

Your fnaify may be outdated. 2.3 should soon be ready. The MONO_FORCE_COMPAT has been added already: https://github.com/rfht/fnaify/blob/master/fnaify#L1013

**Comment by rfht** [comment]
added the symlinking into fnaify: https://github.com/rfht/fnaify/commit/9837f1509d32a4e0bc0c961cac3fc8ac3efc1f7e

**Comment by rfht** [comment]
the game could probably use some more extensive testing to see if other paths need to be fixed

**Comment by rfht** [comment]
closing...
